config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "toppages#index"
  
  get "works", to: "toppages#works"
  get "about", to: "toppages#about"
  
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      flash[:success] = "お問合せ内容を送信しました"
      redirect_to new_contact_url
    else
      flash.now[:danger] = "お問合せ内容の送信に失敗しました"
      render "contacts/new", status: :unprocessable_entity
    end
  end
  
  
  private
  
  def contact_params
    params.require(:contact).permit(:company, :name, :email, :tel, :message)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
  
  def works
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/contacts/new.html.erb
<h2 class="text-center border-top border-bottom border-dark mt-5">Contact</h2>
<div class="mb-5">
    <p class="mt-5">
        ご意見・ご相談等ございましたらお気軽にお問い合わせください。<br>
        下記フォームよりわかる範囲でご記入ください。必須の項目は必ずご記入ください。
    </p>
</div>
<%= render "layouts/flash_messages" %>
<div class="row">
    <div class="col-lg-8">
        <%= form_with(model: @contact) do |f| %>
        <%= render "layouts/error_messages", model: f.object %>
            <div>
                <%= f.label :company, "貴社名" %>
                <%= f.text_field :company, class: "form-control mb-2" %>
            </div>
            <div>
                <%= f.label :name, "お名前 ※必須" %>
                <%= f.text_field :name, class: "form-control mb-2" %>
            </div>
            <div>
                <%= f.label :email, "Email ※必須" %>
                <%= f.email_field :email, class: "form-control mb-2" %>
            </div>
            <div>
                <%= f.label :tel, "Tel" %>
                <%= f.telephone_field :tel, class: "form-control mb-2" %>
            </div>
            <div>
                <%= f.label :message, "お問合せ内容 ※必須" %>
                <%= f.text_area :message, class: "form-control mb-2" %>
            </div>
            <%= f.submit "送信", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert_warning" >
        <ul class="mb-0">
            <% model.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %>"><%= msg %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand fs-3" href="/">Tech.Tomita</a>
            <!--折りたたみボタン -->
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSC">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- 画面サイズに合わせて折り畳む -->
            <div id="navbarSC" class="collapse navbar-collapse justify-content-end">
                <ul class="navbar-nav fw-bold fs-5">
                    <li class="nav-item ms-5 me-5"><%= link_to "Works", works_path, class: "nav-link" %></li>
                    <li class="nav-item ms-5 me-5"><%= link_to "About", about_path, class: "nav-link" %></li>
                    <li class="nav-item ms-5 me-5"><%= link_to "Contact", new_contact_path, class: "nav-link" %></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>PortfolioTechTomita</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-turbolinks="false">
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= yield %>
    </div>
    
    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/toppages/about.html.erb
<h2 class="text-center border-top border-bottom border-dark mt-5">Profile</h2>
<div class="row">
    <div class="col-lg-5 mt-5">
        <a href="https://github.com/TechTomita"><img src="./assets/github.png"></a>
    </div>
    <div class="col-lg-7 fs-5 mt-5">
        <ul>
            <li class="mb-3">名前: Takuma Tomita</li>
            <li class="mb-3">出身: 茨城県(現在は千葉在住)</li>
            <li class="mb-5">学歴: 茨城大学　人文学部</li>
        </ul>
        <p class="border-top border-bottom border-dark p-3">
            大学卒業後、ホームセンターに入社。5年間勤務をし、店舗マネジャーを経験。<br>
            入社2年目で業務に活かせるのではないかと、プログラミングの勉強を始める。<br>
            自分自身でも「コンピュータやインターネットではこんな便利なことや面白いことが出来るんだ。」<br>
            という感動を提供する側になりたいと考え、エンジニアへの転身を決意し、転職活動中。<br>
            現在はRuby on Raildを使ったWebアプリ制作に挑戦。
            
        </p>
    </div>
</div>
<div id="link" class="text-center mt-5">
    <a class="m-5" href="https://github.com/TechTomita"><img src="./assets/git_hub.png"></a>
    <a class="m-5" href="<%= new_contact_path %>"><img src="./assets/mail.png"></a>
</div>

app/views/toppages/index.html.erb
<div class="row d-flex mt-4">
    <div class="col-lg-2 fs-4 mt-5 mb-5">
        <p>-Hello!</p>
        <p>My name is <span class="fw-bold">Tomita</span></p>
        <P>
            I'm looking for a new job,<br>
            and interested in working with computers in the future!
        </P>
    </div>
    <div class="col-lg-8 text-center p-0">
        <img id="top-img" class="rounded-3" src="./assets/top-icon.jpg">
    </div>
    <div class="col-lg-2 align-self-end fs-4 mt-5 mb-5">
        <p>My strong area</p>
        <ul class="fs-5">
            <li>Web application</li>
            <li>iOS application</li>
        </ul>
    </div>
</div>

app/views/toppages/works.html.erb
<h2 class="text-center border-top border-bottom border-dark mt-5">My deliverables</h2>
<!-- message-board-app -->
<div class="row d-flex  border-2 border-top border-bottom mt-5">
    <div class="col-lg-8">
        <img src="./assets/message-board-app.png">
    </div>
    <div class="col-lg-4 text-center">
        <a id="message-board-app" href="https://message-board-app-techtomita.herokuapp.com/"><h2>message-board-app</h2></a>
        <p>Ruby on Rails / JavaScript / MySQL</p>
        <div class="text-start mt-5">
            <h3 class="text-start">Overview</h3>
            <p>掲示板アプリ</p>
            <p>タイトルをつけて、メッセージの投稿ができます。</p>
        </div>
        <a href="https://github.com/TechTomita/practice_Rails_Web_Sanple"><p class="bg-dark text-light text-center mt-5">GitHub</p></a>
    </div>
</div>
<!-- Emotions & snap -->
<div class="row d-flex border-2 border-top border-bottom mt-5">
    <div class="col-lg-4 text-center">
        <a id="emotions-and-snap" href="https://emotions-and-snap.herokuapp.com/"><h2>Emotins & Snap</h2></a>
        <p>Ruby on Rails / JavaScript / MySQL / AWS</p>
        <p>※ under development</p>
        <div class="text-start mt-5">
            <h3 class="text-start">Overview</h3>
            <p>写真共有アプリ</p>
            <p>
                写真を取った時の気持ちを共有してみませんか？<br>
                写真と共にコメントを投稿できます。忘れられない日常の1コマをぜひ共有しましょう!
            </p>
        </div>
        <a href="https://github.com/TechTomita/emotions_and_snap"><p class="bg-dark text-light text-center mt-5">GitHub</p></a>
    </div>
    <div class="col-lg-8">
        <img src="./assets/emotions-and-snap.png">
    </div>
</div>
<!-- microposts -->
<div class="row d-flex border-2 border-top border-bottom mt-5">
    <div class="col-lg-8">
        <img src="./assets/microposts.png">
    </div>
    <div class="col-lg-4 text-center">
        <a id="microposts" href="https://micropost-app-tech-tomita.herokuapp.com/"><h2>microposts</h2></a>
        <p>Ruby on Rails / JavaScript / MySQL</p>
        <div class="text-start mt-5">
            <h3>Overview</h3>
            <p>メッセージ共有アプリ</p>
            <p>ユーザ登録をすることで、メッセージの投稿・お気に入り登録ができます。他ユーザをフォローして、メッセージの共有をしてみてはいかがですか?</p>
        </div>
        <a href="https://github.com/TechTomita/Sample_RubyonRails_Web_microposts"><p class="bg-dark text-light text-center mt-5">GitHub</p></a>
    </div>
</div>